name: Pipeline
on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0

      - name: Roda outro comando!
        run: echo $(ls)
