name: Pipeline
on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0

      - name: Setup Python
        uses: actions/setup-python@v3.1.3
        with:
          python-version: "3.10"
